USE [master]
GO
DROP DATABASE IF EXISTS [SEDC] 
GO
CREATE DATABASE [SEDC]
GO
USE [SEDC]
GO


-- ***** CREATE *****
-- create new database object (database, table, view, procedure etc...)
-- dbo (database object) => default schema 
-- NOTE: In the official MS documentation it can be found that naming of database tables should be with singular nouns. HOWEVER, on some projects plural names are used.

CREATE TABLE Customer (
	Id INT NOT NULL,
	FirstName NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	City NVARCHAR(20) NULL
)
GO
SELECT * FROM dbo.Customer


-- ***** INSERT *****
-- insert new records in table

INSERT INTO dbo.Customer (Id, FirstName, LastName, City) -- the columns we are inserting in
VALUES (1, 'Bob', 'Bobsky', 'Skopje') -- must use single quoutes for text types

INSERT INTO dbo.Customer (Id, FirstName, LastName)
VALUES (2, 'John', 'Doe')


-- ***** DROP *****
-- deletes database objects
--DROP TABLE dbo.Customer


-- CREATE dbo.Customer TABLE (with Id as Primary Key and autogenerated)
CREATE TABLE Customer (
	Id INT IDENTITY(1,1) NOT NULL,
	FirstName NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	City NVARCHAR(20) NULL,
	CONSTRAINT PK_Customer_Id PRIMARY KEY CLUSTERED (Id)
)
GO


-- ***** INSERT *****
-- inserting multiple values
INSERT INTO dbo.Customer (FirstName, LastName, City)
VALUES ('Bob', 'Bobsky', 'Skopje'),
	   ('Petko', 'Petkovski', 'Tel Aviv'),
	   ('Greg', 'Gregski', 'Tetovo')


-- ***** ALTER *****
ALTER TABLE dbo.Customer
ALTER COLUMN FirstName nvarchar(100) NOT NULL -- update existing column
GO

ALTER TABLE dbo.Customer
ADD Age int NULL -- add new column
GO

-- ***** SELECT *****
-- showing result from query in a table

SELECT * FROM dbo.Customer

SELECT FirstName, LastName FROM dbo.Customer

SELECT FirstName, LastName, City 
FROM dbo.Customer
WHERE City = 'Skopje'


-- ***** UPDATE *****
-- update values in tables
-- Example: update specific records only
UPDATE dbo.Customer
SET FirstName = 'Gregory', City = 'Bitola'
WHERE FirstName = 'Greg'
GO

-- update all values
-- City for all records will be set to Tokyo
UPDATE dbo.Customer
SET Age = 29
GO

-- ***** DELETE *****
-- deleting records in tables
-- all records
DELETE 
FROM Customer 
-- specific record(s)
DELETE 
FROM Customer
WHERE FirstName = 'Petko'
